name: build1

on:
  workflow_dispatch:

jobs:
  build_ffmpeg:
    name: Build ffmpeg
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [win32]
        variant: [gpl-shared 4.2,lgpl-shared 4.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build ffmpeg
        run: ./build.sh ${{ matrix.target }} ${{ matrix.variant }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg
          path: artifacts/*
