name: Build FFmpeg

on:
  workflow_dispatch:
env:
  DOCKER_BUILDKIT: 1

jobs:
  purge_artifacts:
    name: Purge old artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Purge old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 0 days
          skip-recent: 3
  build_base:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Image Name
        id: imagename
        run: echo "::set-output name=name::ghcr.io/${GITHUB_REPOSITORY,,}/base:latest"
      - name: Build base image
        run: docker build --pull --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${{ steps.imagename.outputs.name }} --tag ${{ steps.imagename.outputs.name }} images/base
      - name: Push base image
        run: docker push ${{ steps.imagename.outputs.name }}
