name: upload test

on:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_base:
    name: Build base image
    runs-on: ubuntu-latest
    env:
      working-directory: './dockimg'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build base image
        run: |
          ls -R
          docker build --pull --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${{ steps.imagename.outputs.name }} --tag ${{ steps.imagename.outputs.name }} images/base
          ls -R
      - uses: actions/upload-artifact@v2
        with:
          name: agileconfig-ui
          path: ./**/*
