name: test

on:
  workflow_dispatch:

jobs:
  test:
    name: script test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master        
      - name: test script
        run:  ./test.sh
