name: upload dockimg

on:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_base:
    name: Build base image
    runs-on: ubuntu-latest
    env:
      working-directory: './dockimg'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tag: aaa-bbb-1.1.1
          build-args: |
            ffmpeg-build         
      - name: Image Name
        id: imagename
        run: |
          echo "::set-output name=name::giantsoft2dock/${GITHUB_REPOSITORY,,}/base:latest" 
          ls -R
      - name: Build base image
        run: |
          docker build --pull --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${{ steps.imagename.outputs.name }} --tag ${{ steps.imagename.outputs.name }} images/base 
          ls -R
      - name: dir list
        run: ls -R
        working-directory: ${{ env.working-directory }}
      - uses: actions/upload-artifact@v2
        with:
          name: agileconfig-ui
          path: dockimg/
      - name: Push base image
        run: docker push ${{ steps.imagename.outputs.name }}
